[build]
  publish = "build"
  command = "npm install --no-audit --no-fund --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "16"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 