"""Initial migration

Revision ID: e3d684f2475e
Revises: 
Create Date: 2025-08-16 02:34:42.121843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d684f2475e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('products', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'products', ['sku'])
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('products', 'last_updated')
    op.drop_column('products', 'status')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'max_stock')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'price')
    op.drop_column('products', 'supplier')
    # ### end Alembic commands ###
